{"name": "test_login_failure", "status": "passed", "attachments": [{"name": "stdout", "source": "b0d6ceba-d6b8-49f0-9624-34b9285b171b-attachment.txt", "type": "text/plain"}], "start": 1749496566280, "stop": 1749496566572, "uuid": "ce112d90-3cf8-426d-8238-37c2e2e23e6f", "historyId": "4038fcb77af2b80eea832d3a3633d3c6", "testCaseId": "4038fcb77af2b80eea832d3a3633d3c6", "fullName": "tests.views.test_auth_views#test_login_failure", "labels": [{"name": "parentSuite", "value": "tests.views"}, {"name": "suite", "value": "test_auth_views"}, {"name": "host", "value": "PC-5CG4282G66"}, {"name": "thread", "value": "38368-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.views.test_auth_views"}]}